project:
  type: website

website:
  title: "Vinicius Oike"
  site-url: https:://www.restateinsight.com
  google-analytics: "G-EJF8PGT67H"
  comments:
    giscus:
      repo: viniciusoike/restateinsight
  description: A blog on economics and cities
  navbar:
    right:
      - text: Blog
        href: blog.qmd
      - text: Sobre
        href: aboutme.qmd
      - text: Apps
        href: my_apps.qmd
      - text: Imprensa
        href: press.qmd
      - icon: github
        href: https://github.com/viniciusoike
      - icon: twitter
        href: https://twitter.com/viniciusoike
      - text: Archive
        href: archive.qmd
format:
  html:
    theme: [lumen, mystyles.scss]
    mainfont: Questrial
    toc: true
    css: styles.css
    highlight-style: atom-one

editor: visual

