---
title: "Imprensa"
about:
  template: solana
  links:
    - icon: linkedin
      text: LinkedIn
      href: "https://www.linkedin.com/in/vinicius-oike-993826a9/"
    - icon: github
      text: Github
      href: "https://github.com/viniciusoike"
    - icon: twitter
      text: Twitter
      href: "https://twitter.com/viniciusoike"
comments: false
---

# Na Imprensa

Em certas ocasiões, sou convidado para participar de matérias sobre mercado imobiliário na imprensa. Em outros casos, estudos que fiz ganham repercussão nos meios de comunicação. Aqui destaco algumas das publicações mais relevantes.

## 2023

-   **\[BBC\] [Nômades digitais e aluguel em dólar: por que moradores estão sendo expulsos de seus bairros na América Latina](https://www.bbc.com/portuguese/articles/cy0p1z80yelo)**

-   **\[BBC\] [Cuánto se han disparado los alquileres en las mayores ciudades de América Latina y qué posibilidades hay de que bajen](https://www.bbc.com/mundo/noticias-65703911)**

-   **\[BBC\] [O que explica disparada de aluguéis nas maiores cidades da América Latina?](https://www.bbc.com/portuguese/articles/cq5qrlpyxjgo)**

-   **\[BBC\] [O que explica alta do aluguel residencial acima da inflação e o que esperar em 2023](https://www.bbc.com/portuguese/brasil-64455893)**

-   **\[CBN\] [Entenda o movimento de alta dos aluguéis e de queda no valor de compra de imóveis](https://cbn.globoradio.globo.com/media/audio/406456/entenda-o-movimento-de-alta-dos-alugueis-e-de-qued.htm)**

-   **\[Folha de SP\] [Aluguel de apartamento com 1 quarto cai em SP, diz pesquisa](https://www1.folha.uol.com.br/mercado/2023/05/aluguel-de-apartamento-com-1-quarto-cai-em-sp-diz-pesquisa.shtml)**

-   **\[InvestNews\] [Aluguel em SP e RJ tem a maior alta nos últimos 3 anos, segundo Quinto Andar](https://investnews.com.br/financas/aluguel-em-sp-e-rj-tem-a-maior-alta-nos-ultimos-anos-segundo-quinto-andar/)**

-   **\[Forbes\] [Aluguéis em SP sobem mais do que a inflação no 1ºtrimestre](https://forbes.com.br/forbes-money/2023/04/alugueis-em-sp-sobem-mais-do-que-a-inflacao-no-1o-trimestre/)**

-   **\[G1\] [O que explica alta do aluguel residencial acima da inflação e o que esperar em 2023](https://g1.globo.com/economia/noticia/2023/02/04/o-que-explica-alta-do-aluguel-residencial-acima-da-inflacao-e-o-que-esperar-em-2023.ghtml)**

-   **\[G1\] [Mercado de imóveis de luxo cresce no Brasil e preços passam dos R\$ 40 milhões; veja apartamentos por dentro](https://g1.globo.com/economia/noticia/2023/07/23/mercado-de-imoveis-de-luxo-cresce-no-brasil-e-precos-passam-dos-r-40-milhoes-veja-apartamentos-por-dentro.ghtml)**

-   **\[G1 RS\] [Microapartamentos: aluguel médio de imóvel com até 30m² em Porto Alegre é de R\$ 860](https://g1.globo.com/rs/rio-grande-do-sul/noticia/2023/01/25/microapartamentos-aluguel-medio-de-imovel-com-ate-30m-em-porto-alegre-e-de-r-860-aponta-estudo.ghtml)**

-   **\[Rede Minas TV\] [A BUSCA POR MICROAPARTAMENTOS É REFLEXO DE UMA NOVA DINÂMICA SOCIAL](https://www.youtube.com/watch?v=4qMK0p16Dzg)**

-   **\[Valor\] [Incorporadoras perdem margem e lucro e veem 2023 difícil](https://valor.globo.com/empresas/noticia/2022/11/30/incorporadoras-perdem-margem-e-lucro-e-veem-2023-dificil.ghtml)**

-   **\[Veja SP\] [São Paulo teve aumento de 15,5% no aluguel em 2022](https://vejasp.abril.com.br/cidades/sao-paulo-teve-aumento-de-155-no-aluguel-em-2022)**

## 2022

-   **\[Abecip\] [Rio é a 6ª capital mais cara para comprar imóvel na América Latina](https://www.abecip.org.br/imprensa/noticias/rio-e-a-6-capital-mais-cara-para-comprar-imovel-na-america-latina-veja)**

-   **\[El Economista\] [CDMX quiere ser el hogar de los nómadas digitales con ayuda de Airbnb](https://www.eleconomista.com.mx/estados/CDMX-quiere-ser-el-hogar-de-los-nomadas-digitales-con-ayuda-de-Airbnb-20221026-0081.html)**

-   **\[Estadão\] [Preço de Aluguel de Microapartamentos em SP bate recorde após 6a alta seguida](https://www.estadao.com.br/economia/aluguel-microapartamentos-sao-paulo-novembro/)**

-   **\[Folha de SP\] [Tamanho mínimo de casa vai de 8 a 25 metros quadrados em capitais brasileiras](https://www1.folha.uol.com.br/mercado/2023/07/tamanho-minimo-de-casa-vai-de-8-a-25-metros-quadrados-em-capitais-brasileiras.shtml)**

-   **\[G1\] [Comprar imóvel é mais barato no Brasil em relação à América Latina, mas valor ainda pesa no bolso das famílias, diz pesquisa](https://g1.globo.com/economia/noticia/2022/09/29/comprar-imovel-e-mais-barato-no-brasil-em-relacao-a-america-latina-mas-valor-ainda-pesa-no-bolso-das-familias-diz-pesquisa.ghtml)**

-   **\[Imobi Report\] [Em alta ou em queda? Entenda o momento dos microapartamentos](https://imobireport.com.br/em-alta-ou-em-queda-entenda-o-momento-dos-microapartamentos/)**

-   **\[Real Estate Market\] [CDMX y Buenos Aires tienen el alquiler más caro en LATAM](https://www.realestatemarket.com.mx/noticias/mercado-inmobiliario/39400-cdmx-y-buenos-aires-tienen-el-alquiler-mas-caro-en-latam)**

-   **\[R7\] [Porto Alegre, Curitiba, Salvador e BH são as cidades mais baratas para morar na América Latina](https://noticias.r7.com/economia/porto-alegre-curitiba-salvador-e-bh-sao-as-cidades-mais-baratas-para-morar-na-america-latina-30092022)**

-   **\[Nacion MX\] [ESTUDIO EN LATAM NOS DA PANORAMA DE REAL ESTATE EN MÉXICO](https://nacionmx.com/2022/10/31/estudio-en-latam-nos-da-panorama-de-real-estate-en-mexico/)**

-   **\[Valor\] [Incorporadoras perdem margem e lucro e veem 2023 difícil](https://valor.globo.com/empresas/noticia/2022/11/30/incorporadoras-perdem-margem-e-lucro-e-veem-2023-dificil.ghtml)**

-   **\[QA\] [Mercado residencial na América Latina: QuintoAndar faz estudo inédito em 12 cidades de seis países](https://conteudos.quintoandar.com.br/mercado-residencial-america-latina/)**

-   **\[QA\] [Tendências do mercado imobiliário: o que a economia nos aponta?](https://conteudos.quintoandar.com.br/tendencias-mercado-imobiliario-2023/)**

## 2021

-   **\[Folha de SP\] [Apenas os 10% mais ricos podem comprar imóvel acima de R\$ 600 mil em SP, diz pesquisa](https://www1.folha.uol.com.br/mercado/2021/10/apenas-os-10-mais-ricos-podem-comprar-imovel-acima-de-r-600-mil-em-sp-diz-pesquisa.shtml)**

-   **\[Abecip\] [Apenas os 10% mais ricos podem comprar imóvel acima de R\$ 600 mil em SP](https://www.abecip.org.br/imprensa/noticias/apenas-os-10-mais-ricos-podem-comprar-imovel-acima-de-r-600-mil-em-sp-diz-pesquisa)**

-   **\[G1 SP\] [Casal com dois filhos e renda mediana em SP só consegue comprar imóvel com mais de 40m² longe do Centro](https://g1.globo.com/sp/sao-paulo/noticia/2021/10/27/casal-com-dois-filhos-e-renda-mediana-em-sp-so-consegue-comprar-imovel-com-mais-de-40m-longe-do-centro-mostra-pesquisa.ghtml)**
