---
title: 'Censo 2022 e a Região Sul'
date: '2023-07-03'
categories: ['data-visualization', 'ggplot2', 'tutorial-R']
draft: true
---

```{r}
knitr::opts_chunk$set(eval = FALSE)

library(sidrar)
library(dplyr)
library(tidyr)
library(ggplot2)
library(geobr)
library(sf)
```

```{r, include=FALSE}
cities00 <- geobr::read_municipality(year = 2000)
cities10 <- geobr::read_municipality(year = 2010)
cities20 <- geobr::read_municipality(year = 2020)

dim_city <- as_tibble(st_drop_geometry(cities20))

```

```{r}

pop2022 <- get_sidra(4709, geo = "City")



info_sidra(4709)
4712

136
4709
```

```{r}
census_pop <- get_sidra(
  136,
  period = "1991-2010",
  variable = 93,
  geo = "City",
  classific = "c86",
  category = list(0)
  )
```

```{r}
census_pop <- census_pop %>%
  janitor::clean_names() %>%
  select(code_muni = municipio_codigo, year = ano, pop = valor) %>%
  mutate(code_muni = as.numeric(code_muni)) %>%
  group_by(code_muni) %>%
  mutate(chg_abs = pop - lag(pop), chg = pop / lag(pop) - 1) %>%
  ungroup()

south <- census_pop %>%
  mutate(code_region = as.numeric(substr(code_muni, 1, 1))) %>%
  filter(code_region == 4)

```

```{r}
south_cities <- south %>%
  left_join(dim_city, by = c("code_muni", "code_region")) %>%
  filter(pop > 50000)
```

```{r}
tbl_south <- south %>%
  pivot_wider(
    id_cols = "code_muni",
    names_from = "year",
    values_from = c("pop", "chg")
  )

pop_cities <- cities20 %>%
  filter(code_region == 4) %>%
  left_join(tbl_south, by = "code_muni")
```

```{r}
ggplot(pop_cities, aes(x = log(pop_2010), y = chg_2010)) +
  geom_point(alpha = 0.5, aes(color = as.factor(abbrev_state)))
```

```{r}
pop_cities %>%
  mutate(
    group = ntile()
  )


ggplot(pop_cities) +
  geom_sf(aes(fill = chg_2010), size = 0.1) +
  theme_void()
```

```{r}
top_cities <- tbl_south %>%
  left_join(dim_city) %>%
  group_by(code_state) %>%
  slice_max(pop_2000, n = 10) %>%
  ungroup() %>%
  mutate(name_muni = factor(name_muni), name_muni = forcats::fct_reorder(name_muni, pop_2000))
  

top_cities %>%
  select(name_muni, abbrev_state, pop_1991:pop_2010) %>%
  pivot_longer(pop_1991:pop_2010, names_sep = "_", names_to = c("var", "year")) %>%
  ggplot(aes(x = name_muni, y = value / 1000, fill = as.factor(year))) +
  geom_col(position = position_dodge()) +
  facet_wrap(vars(abbrev_state), scales = "free") +
  scale_x_discrete(labels = \(x) stringr::str_wrap(x, width = 8)) +
  scale_y_continuous(labels = scales::label_number(big.mark = ".")) +
  scale_fill_manual(
    name = "Ano",
    values = rev(c("#0FA3B1", "#8CD3E8", "#B5E2FA"))
  ) +
  coord_flip() +
  labs(
    x = NULL,
    y = "Populacao (1000)"
  ) +
  theme_light() +
  theme(
    legend.background = element_rect(fill = "#F9F7F3", color = NA),
    panel.background = element_rect(fill = "#F9F7F3", color = NA),
    plot.background = element_rect(fill = "#F9F7F3", color = NA),
    panel.grid.minor = element_blank(),
    panel.grid.major.y = element_blank(),
    legend.position = "top",
    axis.text.y = element_text(hjust = 0.5)
  )
  
  
```
