{
  "hash": "e6e41b89437862d721462ef7ef4eb1dd",
  "result": {
    "markdown": "---\ntitle: \"ARMA: um exemplo simples\"\ndate: \"2021-03-01\"\ndescription: \"Neste post mostro como modelar um ARMA simples no R usando o pacote {astsa}.\"\ncategories: [\"econometria\", \"time-series\", \"repost\", \"tutorial-R\"]\nexecute: \n  message: false\n  warning: false\nknitr:\n  opts_chunk:\n    out.width: '100%'\n    collapse: true\n    comment: \"#>\"\n---\n\n::: {.cell}\n\n:::\n\n\n# Introdução\n\nNeste post apresento como estimar e diagnosticar um modelo ARMA simples no R. O modelo ARMA decompõe uma série em função de suas observações passadas e de \"passados\" (às vezes chamados de inovações). O ARMA(1, 1) com constante tem a seguinte forma.\n\n$$\ny_{t} = \\phi_{0} +\\phi_{1}y_{t-1} + \\varepsilon_{t} + \\theta_{1}\\varepsilon_{t - 1}\n$$\n\nonde ambas as condições de estacionaridade como de invertibilidade devem ser atendidas. Assume-se que o termo $\\varepsilon_{t}$ é um ruído branco. De maneira mais geral, um modelo ARMA(p, q) tem a forma:\n\n$$\ny_{t} = \\phi_{0} +\\phi_{1}y_{t-1} + \\dots + \\phi_{p}y_{t-p} + \\varepsilon_{t} + \\theta_{1}\\varepsilon_{t - 1} + \\dots + \\theta_{q}\\varepsilon_{t- q}\n$$\n\n# Crescimento do PNB\n\nVamos usar a série do PNB disponbilizada pelo pacote `astsa`. Este pacote foi montado pelos autores do livro [Time Series Analysis](https://www.stat.pitt.edu/stoffer/tsa4/). Para visualizar a série usamos a função `plot.ts`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(astsa)\nlibrary(forecast)\ndata(\"gnp\")\n```\n:::\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot.ts(gnp,\n        main = \"Produto Nacional Bruto EUA (trimestre)\",\n        xlab = \"\",\n        ylab = \"US$ (bilhões)\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-3-1.svg){fig-align='center' width=90%}\n:::\n:::\n\n\nPrecisamos transformar a série primeiro. Para encontrar a variação percentual de uma variável $y_{t}$ qualquer fazemos\n\n$$\n  \\Delta y_{t} = \\frac{y_{t} - y_{t-1}}{y_{t-1}}\n$$\n\nUma aproximação comumumente usada no lugar da equação acima é a diferença em log. Na literatura de finanças a equação acima também é conhecida como *retorno* e a diferença em log como *log-retorno*. Na prática, além da aproximação ser boa para valores pequenos (em torno de zero) costuma ser mais cômodo trabalhar com log-retornos.\n\n$$\n  \\Delta y_{t} = \\frac{y_{t} - y_{t-1}}{y_{t-1}} \\approx \\text{ln}(1 + \\Delta y_{t}) = \\text{ln}(y_{t}/y_{t-1}) = \\text{ln}(y_{t}) - \\text{ln}(y_{t-1})\n$$\n\nNo R podemos combinar duas funções para facilitar o cômputo da diferença dos logs: usamos `diff()` que computa $y_{t} - y_{t - 1}$ junto com a função `log()` que computa o logaritmo. Note que a função `log()` usa o número $e$ como base; é possível trocar a base usando o argumento `base = 10`, por exemplo, ou usar simplesmente uma outra função `log10()`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Computa log(y[t]) - log(y[t-1])\ny <- diff(log(gnp))\n# Gráfico da série transformada\nplot.ts(y * 100, main = \"Variação percentual do PIB\", xlab = \"\", ylab = \"(%)\")\nabline(h = 0, col = \"gray30\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-4-1.svg){fig-align='center' width=90%}\n:::\n:::\n\n\nPara avaliar a qualidade do modelo vamos reservar a parte final dos dados: a ideia é gerar previsões usando apenas a informação da primeira parte da amostra e então comparar estas previsões com as observações. Esta metodologia às vezes é denominada de *train* (treino) e *test* (teste).\n\nTreinamos o modelo com as primeiras observações e depois testamos as suas previsões contra as observações finais (que ficaram fora do modelo). Aqui também cabe uma breve observação sobre dados em série de tempo. Se tivéssemos dados em cross-section o correto seria formar as bases *train* e *test* usando algum tipo de amostragem aleatória. Como os dados de série de tempo são encadeados não podemos fazer isto: por isto \"cortamos\" as observações num determinado instante do tempo.\n\nAbaixo escolho um tanto arbitrariamente cortar os dados em janeiro de 1992. Em azul destaco os dados que serão utilizados para alimentar o modelo. As previsões serão testasdas contra as observações em vermelho.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Cria a janela temporal\ntrain <- window(y, end = c(1991, 4))\nteste <- window(y, start = c(1992, 1))\n\n# Plota o gráfico destacando as observações finais que foram removidas.\nplot.ts(y)\nlines(train, col = \"blue\")\nlines(teste, col = \"red\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-5-1.svg){fig-align='center' width=90%}\n:::\n:::\n\n\n# Identificação\n\nO primeiro trabalho que temos é o de identificar a ordem do modelo, isto é, encontrar os valores verdadeiros de $p$ e $q$. A maneira mais comum de começar é tentar comparar os gráficos das funções de autocorrelação (FAC) e autocorrelação parcial (FACP) com suas contrapartidas teóricas. O R tem as funções `acf()` e `pacf()` que calculam estes valores junto com intervalos de confiança assintóticos.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Modifica parâmetros para apresentar dois gráficos numa mesma figura\npar(mfrow = c(2, 1))\nacf(train,  main = \"Função de autocorrelação\", xlab = \"Defasagem\", ylab = \"ACF\")\npacf(train, main = \"Função de autocorrelação parcial\", xlab = \"Defasagem\", ylab = \"PACF\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-6-1.svg){fig-align='center' width=90%}\n:::\n:::\n\n\nNote que a escala das defasagens é agrupada pela frequência dos dados, isto é, são contadas de quatro em quatro. Há alguns problemas com a visualização acima. Primeiro, a função de autocorrelãção começa no lag zero, isto é, $\\rho(0)$. Sabemos que este valor sempre será igual a um pois, por definição: $\\rho(0) = \\frac{\\gamma(0)}{\\gamma(0)} = 1$. Logo, seria melhor que esta defasagem fosse suprimida. Além disso, é um tanto inconveniente ter que modificar os parâmetros gráficos usando `par(mfrow = c(2, 1))`. Uma saída é usar a função `acf2()` do pacote `astsa`. Esta função também imprime uma lista com os valores estimados da FAC e da FACP.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nacf2(train)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-7-1.svg){fig-align='center' width=90%}\n:::\n\n```\n#>      [,1] [,2]  [,3]  [,4]  [,5]  [,6]  [,7]  [,8] [,9] [,10] [,11] [,12] [,13]\n#> ACF  0.36 0.19 -0.01 -0.13 -0.17 -0.11 -0.09 -0.05 0.04  0.05  0.03 -0.12 -0.13\n#> PACF 0.36 0.07 -0.12 -0.12 -0.08  0.00 -0.03 -0.02 0.05  0.01 -0.03 -0.18 -0.05\n#>      [,14] [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24]\n#> ACF  -0.10 -0.11  0.05  0.08  0.11  0.06  0.07 -0.08 -0.05 -0.10 -0.06\n#> PACF  0.02 -0.07  0.10  0.02  0.02 -0.04  0.02 -0.11  0.03 -0.03 -0.01\n```\n:::\n\n\nAgora está mais claro que as duas primeiras defasagens da FAC são significantes e que a primeira defasagem da FACP é significante. Note também que a 5ª defasagem na FAC é um pouco significante e há uma defasagem de ordem elevada (lag 12) que é um pouco significante na FACP. Em geral, podemos desprezar estas autocorrelações de ordens muito elevadas até porque vamos querer modelos mais parcimoniosos (i.e. com poucos parâmetros).\n\nApenas olhando para os gráficos acima poderíamos chutar um modelo ARMA(1,1), ARMA(1,2) ou mesmo um AR(1). Depois disto teríamos que checar os resíduos para ver se o modelo está bem ajustado. Por fim, poderíamos escolher o melhor modelo segundo algum critério de informação como o Critério de Akaike (AIC). Alternativamente, poderíamos identificar a ordem do modelo usando algum algoritmo. A função `auto.arima()` do pacote `forecast()` verifica vários modelos e compara eles via uma série de critérios.\n\n# Estimação e diagnóstico\n\n## Modelo 1\n\nVou primeiro estimar o ARMA(1, 2) usando a função `arima()` do R.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n(m1 <- arima(train, order = c(1, 0, 2)))\n#> \n#> Call:\n#> arima(x = train, order = c(1, 0, 2))\n#> \n#> Coefficients:\n#>          ar1     ma1     ma2  intercept\n#>       0.2324  0.0971  0.1623     0.0084\n#> s.e.  0.2294  0.2247  0.0958     0.0012\n#> \n#> sigma^2 estimated as 0.0001038:  log likelihood = 566.91,  aic = -1123.82\n```\n:::\n\n\nA estimativa tem a forma: $$\n  y_{t} = \\underset{(0.0012)}{0.0084} + \\underset{(0.2324)}{0.2294}y_{t - 1} + \\underset{(0.2247)}{0.0971}\\epsilon_{t-1} + \\underset{(0.0958)}{0.1623}\\epsilon_{t-2}\n$$ Note que os erros-padrão de $\\hat{\\phi_{1}}$ e $\\hat{\\theta_{1}}$ são bastante elevados. De fato, um teste-t revela que estes coeficientes não são significantes.\n\n### Diagnóstico de resíduos\n\nPode-se verificar os resíduos do modelo de muitas formas. Idealmente, quer-se que os resíduos não apresentem autocorrelação alguma. Uma forma gráfica de ver isto é usando a função `lag1.plot` que apresenta gráficos de dispersão entre o resíduo $u_{t}$ contra suas defasagens $u_{t-1}, u_{t-2}, \\dots$. Abaixo faço isto para as primieras quatro defasagens.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nresiduos <- resid(m1)\nlag1.plot(residuos, max.lag = 4)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-9-1.svg){fig-align='center' width=90%}\n:::\n:::\n\n\nNa prática, é mais conveniente analisar diretamente os gráficos da FAC e da FACP dos resíduos.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nacf2(residuos)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-10-1.svg){fig-align='center' width=90%}\n:::\n\n```\n#>      [,1]  [,2] [,3]  [,4]  [,5]  [,6]  [,7]  [,8] [,9] [,10] [,11] [,12] [,13]\n#> ACF  0.01 -0.01    0 -0.09 -0.12 -0.03 -0.04 -0.05 0.04  0.06  0.07 -0.12 -0.07\n#> PACF 0.01 -0.01    0 -0.09 -0.12 -0.03 -0.05 -0.06 0.02  0.04  0.06 -0.15 -0.09\n#>      [,14] [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24]\n#> ACF  -0.03 -0.12  0.07  0.06  0.06  0.02  0.09  -0.1  0.00 -0.07 -0.04\n#> PACF -0.02 -0.11  0.06  0.02  0.04 -0.02  0.05  -0.1  0.01 -0.05 -0.01\n```\n:::\n\n\nUm teste basatante usual para verificar a presença de autocorrelação nos resíduos é o Ljung-Box. Para computá-lo uso a função `Box.test()` do pacote `tseries`. Note que é preciso suplementar o argumento `fitdf` com o número de parâmetros estimados do modelo. Isto serve para corrigir a estatística do teste. A escolha da ordem do teste é um tanto arbitrária e, na prática, seria recomendado fazer o teste para várias ordens diferentes. O código abaixo computa a estatística do teste para uma defasagem igual a 8.\n\nNote o uso do argumento `fitdf` que leva em conta o número de parâmetros estimados no modelo. Segundo o p-valor, não temos evidência para rejeitar a hipótese nula de que os resíduos *não* são conjuntamente autocorrelacionados. Isto é, temos evidência de que o modelo está bem ajustado pois os resíduos parecem se comportar como ruído branco.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(tseries)\nBox.test(residuos, type = \"Ljung-Box\", lag = 8, fitdf = 4)\n#> \n#> \tBox-Ljung test\n#> \n#> data:  residuos\n#> X-squared = 4.9486, df = 4, p-value = 0.2926\n```\n:::\n\n\nNa prática, é bom repetir o teste para várias defasagens diferentes. A tabela abaixo resume os valores do teste para várias ordens de defasagem. Vale lembrar que o teste Ljung-Box tende a não-rejeitar H0 para defasagens muito elevadas.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-bordered\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:center;\"> Defasagem </th>\n   <th style=\"text-align:center;\"> Estatística de teste </th>\n   <th style=\"text-align:center;\"> P-valor </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:center;\"> 8 </td>\n   <td style=\"text-align:center;\"> 4.9486 </td>\n   <td style=\"text-align:center;\"> 0.2926 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> 9 </td>\n   <td style=\"text-align:center;\"> 5.2251 </td>\n   <td style=\"text-align:center;\"> 0.3890 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> 10 </td>\n   <td style=\"text-align:center;\"> 5.8669 </td>\n   <td style=\"text-align:center;\"> 0.4383 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> 11 </td>\n   <td style=\"text-align:center;\"> 6.7991 </td>\n   <td style=\"text-align:center;\"> 0.4501 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> 12 </td>\n   <td style=\"text-align:center;\"> 9.7788 </td>\n   <td style=\"text-align:center;\"> 0.2809 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> 13 </td>\n   <td style=\"text-align:center;\"> 10.8054 </td>\n   <td style=\"text-align:center;\"> 0.2893 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> 14 </td>\n   <td style=\"text-align:center;\"> 10.9313 </td>\n   <td style=\"text-align:center;\"> 0.3629 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> 15 </td>\n   <td style=\"text-align:center;\"> 13.6377 </td>\n   <td style=\"text-align:center;\"> 0.2537 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> 16 </td>\n   <td style=\"text-align:center;\"> 14.5903 </td>\n   <td style=\"text-align:center;\"> 0.2646 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> 17 </td>\n   <td style=\"text-align:center;\"> 15.2158 </td>\n   <td style=\"text-align:center;\"> 0.2941 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> 18 </td>\n   <td style=\"text-align:center;\"> 15.8735 </td>\n   <td style=\"text-align:center;\"> 0.3212 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> 19 </td>\n   <td style=\"text-align:center;\"> 15.9294 </td>\n   <td style=\"text-align:center;\"> 0.3868 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> 20 </td>\n   <td style=\"text-align:center;\"> 17.4548 </td>\n   <td style=\"text-align:center;\"> 0.3568 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n### Usando o pacote `astsa`\n\nUma forma bastante conveniente de trabalhar com modelos ARMA é com a função `sarima` do pacote `astsa`. Esta função apresenta automaticamente algumas valiosas informações para o diagnóstico dos resíduos: o gráfico do ACF, o gráfico qq-plot (para verificar a normalidade dos resíduos) e os p-valores do teste Ljung-Box para várias ordens de defasagem.\n\nA saída abaixo reúne quatro gráficos. O primeiro deles apresenta o resíduo normalizado (ou escalado). Este gráfico não deve apresentar um padrão claro. O segundo gráfico é a FAC do resíduo: idealmente, nenhuma defasagem deve ser significativa neste gráfico. Ao lado da FAC temos o QQ-plot: se todos os pontos caem sobre a linha azul temos evidência de que os resíduos são normalmente distribuídos.\n\nPor fim, o último gráfico mostra o p-valor do teste Ljung-Box (já ajustado pelo número de parâmetros do modelo estimado) para diferentes defasagens. A linha tracejada em azul indica o valor 0.05. Idealmente, todos os pontos devem estar acima desta linha.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsarima(train, p = 1, d = 0, q = 2)\n#> initial  value -4.507231 \n#> iter   2 value -4.512000\n#> iter   3 value -4.582718\n#> iter   4 value -4.583615\n#> iter   5 value -4.583727\n#> iter   6 value -4.583754\n#> iter   7 value -4.583896\n#> iter   8 value -4.583941\n#> iter   9 value -4.583957\n#> iter  10 value -4.583958\n#> iter  10 value -4.583958\n#> final  value -4.583958 \n#> converged\n#> initial  value -4.586016 \n#> iter   2 value -4.586020\n#> iter   3 value -4.586022\n#> iter   4 value -4.586023\n#> iter   5 value -4.586025\n#> iter   6 value -4.586026\n#> iter   7 value -4.586027\n#> iter   8 value -4.586027\n#> iter   9 value -4.586028\n#> iter   9 value -4.586028\n#> iter   9 value -4.586028\n#> final  value -4.586028 \n#> converged\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-13-1.svg){fig-align='center' width=90%}\n:::\n\n```\n#> $fit\n#> \n#> Call:\n#> arima(x = xdata, order = c(p, d, q), seasonal = list(order = c(P, D, Q), period = S), \n#>     xreg = xmean, include.mean = FALSE, transform.pars = trans, fixed = fixed, \n#>     optim.control = list(trace = trc, REPORT = 1, reltol = tol))\n#> \n#> Coefficients:\n#>          ar1     ma1     ma2   xmean\n#>       0.2324  0.0971  0.1623  0.0084\n#> s.e.  0.2294  0.2247  0.0958  0.0012\n#> \n#> sigma^2 estimated as 0.0001038:  log likelihood = 566.91,  aic = -1123.82\n#> \n#> $degrees_of_freedom\n#> [1] 175\n#> \n#> $ttable\n#>       Estimate     SE t.value p.value\n#> ar1     0.2324 0.2294  1.0130  0.3125\n#> ma1     0.0971 0.2247  0.4319  0.6664\n#> ma2     0.1623 0.0958  1.6946  0.0919\n#> xmean   0.0084 0.0012  6.7491  0.0000\n#> \n#> $AIC\n#> [1] -6.278312\n#> \n#> $AICc\n#> [1] -6.277028\n#> \n#> $BIC\n#> [1] -6.189279\n```\n:::\n\n\n## Modelo 2\n\nEstimo também o modelo ARMA(1, 1). A análise de resíduos é análoga à apresentada acima.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nm2 <- arima(train, order = c(1, 0, 1))\n```\n:::\n\n\n## Modelo 3\n\nPara o terceiro modelo uso o método automático do `auto.arima()`. A função escolhe o AR(1) com constante como melhor modelo para representar os dados. Note que a na inspeação visual também tínhamos verificado que o AR(1) seria um possível candidato.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n(m3 <- auto.arima(train))\n#> Series: train \n#> ARIMA(1,0,0) with non-zero mean \n#> \n#> Coefficients:\n#>          ar1    mean\n#>       0.3568  0.0084\n#> s.e.  0.0695  0.0012\n#> \n#> sigma^2 = 0.0001066:  log likelihood = 565.52\n#> AIC=-1125.04   AICc=-1124.91   BIC=-1115.48\n```\n:::\n\n\n### Seleção\n\nPara escolher o melhor modelo pode-se usar algum critério de informação. Abaixo comparo os modelos segundo os critérios AIC, AICc (AIC corrigido) e BIC (Bayesian Information Criterion). Na prática, não é comum que os três critérios escolham o mesmo modelo; em particular, o BIC penaliza o número de parâmetros mais fortemente que o AIC. Neste caso específico, os três critérios escolhem o AR(1).\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-bordered\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:left;\">   </th>\n   <th style=\"text-align:center;\"> AIC </th>\n   <th style=\"text-align:center;\"> AICc </th>\n   <th style=\"text-align:center;\"> BIC </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> ARMA(1, 2) </td>\n   <td style=\"text-align:center;\"> -1123.818 </td>\n   <td style=\"text-align:center;\"> -1124.908 </td>\n   <td style=\"text-align:center;\"> -1115.483 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> ARMA(1, 1) </td>\n   <td style=\"text-align:center;\"> -1123.563 </td>\n   <td style=\"text-align:center;\"> -1124.908 </td>\n   <td style=\"text-align:center;\"> -1115.483 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> AR(1) </td>\n   <td style=\"text-align:center;\"> -1125.045 </td>\n   <td style=\"text-align:center;\"> -1124.908 </td>\n   <td style=\"text-align:center;\"> -1115.483 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n### Previsão\n\nPara gerar previsões usamos a função `forecast()` (outra opção é usar a função base `predict()`). Abaixo computo previsões para os três modelos acima mais um modelo ingênuo que será usado como bench-mark. O modelo ingênuo é simplesmente um random-walk que prevê sempre o valor anterior, isto é, $\\hat{y_{T+1}} = y_{T}$.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nprev1 <- forecast(m1, h = length(teste))\nprev2 <- forecast(m2, h = length(teste))\nprev3 <- forecast(m3, h = length(teste))\nprev4 <- forecast(naive(train, h = length(teste)), h = length(teste))\n\nerros <- t(matrix(c(teste - prev1$mean,\n                    teste - prev2$mean,\n                    teste - prev3$mean,\n                    teste - prev4$mean),\n                    ncol = 4))\nerros <- as.data.frame(erros)\ncolnames(erros) <- paste(\"t =\", as.numeric(time(teste)))\nrow.names(erros) <- c(\"ARMA(1, 2)\",\n                      \"ARMA(1, 1)\",\n                      \"AR(1)\",\n                      \"Y[t+1] = Y[t]\")\n```\n:::\n\n\nOs erros de previsão são apresentados na tabela abaixo.\n\n\n::: {.cell layout-align=\"center\" asis='true'}\n::: {.cell-output-display}\n`````{=html}\n<div style=\"border: 1px solid #ddd; padding: 5px; overflow-x: scroll; width:100%; \"><table class=\"table table-striped table-bordered table-hover\" style=\"margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:left;\">   </th>\n   <th style=\"text-align:center;\"> t = 1992 </th>\n   <th style=\"text-align:center;\"> t = 1992.25 </th>\n   <th style=\"text-align:center;\"> t = 1992.5 </th>\n   <th style=\"text-align:center;\"> t = 1992.75 </th>\n   <th style=\"text-align:center;\"> t = 1993 </th>\n   <th style=\"text-align:center;\"> t = 1993.25 </th>\n   <th style=\"text-align:center;\"> t = 1993.5 </th>\n   <th style=\"text-align:center;\"> t = 1993.75 </th>\n   <th style=\"text-align:center;\"> t = 1994 </th>\n   <th style=\"text-align:center;\"> t = 1994.25 </th>\n   <th style=\"text-align:center;\"> t = 1994.5 </th>\n   <th style=\"text-align:center;\"> t = 1994.75 </th>\n   <th style=\"text-align:center;\"> t = 1995 </th>\n   <th style=\"text-align:center;\"> t = 1995.25 </th>\n   <th style=\"text-align:center;\"> t = 1995.5 </th>\n   <th style=\"text-align:center;\"> t = 1995.75 </th>\n   <th style=\"text-align:center;\"> t = 1996 </th>\n   <th style=\"text-align:center;\"> t = 1996.25 </th>\n   <th style=\"text-align:center;\"> t = 1996.5 </th>\n   <th style=\"text-align:center;\"> t = 1996.75 </th>\n   <th style=\"text-align:center;\"> t = 1997 </th>\n   <th style=\"text-align:center;\"> t = 1997.25 </th>\n   <th style=\"text-align:center;\"> t = 1997.5 </th>\n   <th style=\"text-align:center;\"> t = 1997.75 </th>\n   <th style=\"text-align:center;\"> t = 1998 </th>\n   <th style=\"text-align:center;\"> t = 1998.25 </th>\n   <th style=\"text-align:center;\"> t = 1998.5 </th>\n   <th style=\"text-align:center;\"> t = 1998.75 </th>\n   <th style=\"text-align:center;\"> t = 1999 </th>\n   <th style=\"text-align:center;\"> t = 1999.25 </th>\n   <th style=\"text-align:center;\"> t = 1999.5 </th>\n   <th style=\"text-align:center;\"> t = 1999.75 </th>\n   <th style=\"text-align:center;\"> t = 2000 </th>\n   <th style=\"text-align:center;\"> t = 2000.25 </th>\n   <th style=\"text-align:center;\"> t = 2000.5 </th>\n   <th style=\"text-align:center;\"> t = 2000.75 </th>\n   <th style=\"text-align:center;\"> t = 2001 </th>\n   <th style=\"text-align:center;\"> t = 2001.25 </th>\n   <th style=\"text-align:center;\"> t = 2001.5 </th>\n   <th style=\"text-align:center;\"> t = 2001.75 </th>\n   <th style=\"text-align:center;\"> t = 2002 </th>\n   <th style=\"text-align:center;\"> t = 2002.25 </th>\n   <th style=\"text-align:center;\"> t = 2002.5 </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> ARMA(1, 2) </td>\n   <td style=\"text-align:center;\"> 0.0017385 </td>\n   <td style=\"text-align:center;\"> 0.0009996 </td>\n   <td style=\"text-align:center;\"> -0.0011832 </td>\n   <td style=\"text-align:center;\"> 0.0047685 </td>\n   <td style=\"text-align:center;\"> -0.0075880 </td>\n   <td style=\"text-align:center;\"> -0.0034300 </td>\n   <td style=\"text-align:center;\"> -0.0032720 </td>\n   <td style=\"text-align:center;\"> 0.0041505 </td>\n   <td style=\"text-align:center;\"> 0.0009645 </td>\n   <td style=\"text-align:center;\"> 0.0048053 </td>\n   <td style=\"text-align:center;\"> -0.0031499 </td>\n   <td style=\"text-align:center;\"> 0.0038158 </td>\n   <td style=\"text-align:center;\"> -0.0038534 </td>\n   <td style=\"text-align:center;\"> -0.0059706 </td>\n   <td style=\"text-align:center;\"> -0.0026298 </td>\n   <td style=\"text-align:center;\"> 0.0011636 </td>\n   <td style=\"text-align:center;\"> -0.0008728 </td>\n   <td style=\"text-align:center;\"> 0.0066953 </td>\n   <td style=\"text-align:center;\"> -0.0041940 </td>\n   <td style=\"text-align:center;\"> 0.0035309 </td>\n   <td style=\"text-align:center;\"> 0.0012488 </td>\n   <td style=\"text-align:center;\"> 0.0064862 </td>\n   <td style=\"text-align:center;\"> 0.0012950 </td>\n   <td style=\"text-align:center;\"> -0.0021395 </td>\n   <td style=\"text-align:center;\"> 0.0069883 </td>\n   <td style=\"text-align:center;\"> -0.0032794 </td>\n   <td style=\"text-align:center;\"> -0.0002956 </td>\n   <td style=\"text-align:center;\"> 0.0083934 </td>\n   <td style=\"text-align:center;\"> 0.0023188 </td>\n   <td style=\"text-align:center;\"> -0.0031434 </td>\n   <td style=\"text-align:center;\"> 0.0033963 </td>\n   <td style=\"text-align:center;\"> 0.0099058 </td>\n   <td style=\"text-align:center;\"> -0.0030742 </td>\n   <td style=\"text-align:center;\"> 0.0039295 </td>\n   <td style=\"text-align:center;\"> -0.0078546 </td>\n   <td style=\"text-align:center;\"> -0.0045499 </td>\n   <td style=\"text-align:center;\"> -0.0119065 </td>\n   <td style=\"text-align:center;\"> -0.0103021 </td>\n   <td style=\"text-align:center;\"> -0.0110772 </td>\n   <td style=\"text-align:center;\"> 0.0006393 </td>\n   <td style=\"text-align:center;\"> 0.0005900 </td>\n   <td style=\"text-align:center;\"> -0.0074360 </td>\n   <td style=\"text-align:center;\"> 0.0023173 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> ARMA(1, 1) </td>\n   <td style=\"text-align:center;\"> 0.0015678 </td>\n   <td style=\"text-align:center;\"> 0.0011472 </td>\n   <td style=\"text-align:center;\"> -0.0010609 </td>\n   <td style=\"text-align:center;\"> 0.0048359 </td>\n   <td style=\"text-align:center;\"> -0.0075556 </td>\n   <td style=\"text-align:center;\"> -0.0034158 </td>\n   <td style=\"text-align:center;\"> -0.0032667 </td>\n   <td style=\"text-align:center;\"> 0.0041516 </td>\n   <td style=\"text-align:center;\"> 0.0009637 </td>\n   <td style=\"text-align:center;\"> 0.0048036 </td>\n   <td style=\"text-align:center;\"> -0.0031520 </td>\n   <td style=\"text-align:center;\"> 0.0038136 </td>\n   <td style=\"text-align:center;\"> -0.0038557 </td>\n   <td style=\"text-align:center;\"> -0.0059730 </td>\n   <td style=\"text-align:center;\"> -0.0026323 </td>\n   <td style=\"text-align:center;\"> 0.0011611 </td>\n   <td style=\"text-align:center;\"> -0.0008752 </td>\n   <td style=\"text-align:center;\"> 0.0066928 </td>\n   <td style=\"text-align:center;\"> -0.0041964 </td>\n   <td style=\"text-align:center;\"> 0.0035284 </td>\n   <td style=\"text-align:center;\"> 0.0012464 </td>\n   <td style=\"text-align:center;\"> 0.0064838 </td>\n   <td style=\"text-align:center;\"> 0.0012925 </td>\n   <td style=\"text-align:center;\"> -0.0021420 </td>\n   <td style=\"text-align:center;\"> 0.0069858 </td>\n   <td style=\"text-align:center;\"> -0.0032818 </td>\n   <td style=\"text-align:center;\"> -0.0002980 </td>\n   <td style=\"text-align:center;\"> 0.0083910 </td>\n   <td style=\"text-align:center;\"> 0.0023164 </td>\n   <td style=\"text-align:center;\"> -0.0031458 </td>\n   <td style=\"text-align:center;\"> 0.0033939 </td>\n   <td style=\"text-align:center;\"> 0.0099034 </td>\n   <td style=\"text-align:center;\"> -0.0030766 </td>\n   <td style=\"text-align:center;\"> 0.0039271 </td>\n   <td style=\"text-align:center;\"> -0.0078570 </td>\n   <td style=\"text-align:center;\"> -0.0045523 </td>\n   <td style=\"text-align:center;\"> -0.0119090 </td>\n   <td style=\"text-align:center;\"> -0.0103046 </td>\n   <td style=\"text-align:center;\"> -0.0110796 </td>\n   <td style=\"text-align:center;\"> 0.0006369 </td>\n   <td style=\"text-align:center;\"> 0.0005876 </td>\n   <td style=\"text-align:center;\"> -0.0074384 </td>\n   <td style=\"text-align:center;\"> 0.0023149 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> AR(1) </td>\n   <td style=\"text-align:center;\"> 0.0013079 </td>\n   <td style=\"text-align:center;\"> 0.0009620 </td>\n   <td style=\"text-align:center;\"> -0.0011721 </td>\n   <td style=\"text-align:center;\"> 0.0047728 </td>\n   <td style=\"text-align:center;\"> -0.0075918 </td>\n   <td style=\"text-align:center;\"> -0.0034379 </td>\n   <td style=\"text-align:center;\"> -0.0032817 </td>\n   <td style=\"text-align:center;\"> 0.0041400 </td>\n   <td style=\"text-align:center;\"> 0.0009537 </td>\n   <td style=\"text-align:center;\"> 0.0047944 </td>\n   <td style=\"text-align:center;\"> -0.0031608 </td>\n   <td style=\"text-align:center;\"> 0.0038049 </td>\n   <td style=\"text-align:center;\"> -0.0038643 </td>\n   <td style=\"text-align:center;\"> -0.0059815 </td>\n   <td style=\"text-align:center;\"> -0.0026408 </td>\n   <td style=\"text-align:center;\"> 0.0011526 </td>\n   <td style=\"text-align:center;\"> -0.0008837 </td>\n   <td style=\"text-align:center;\"> 0.0066843 </td>\n   <td style=\"text-align:center;\"> -0.0042049 </td>\n   <td style=\"text-align:center;\"> 0.0035199 </td>\n   <td style=\"text-align:center;\"> 0.0012379 </td>\n   <td style=\"text-align:center;\"> 0.0064753 </td>\n   <td style=\"text-align:center;\"> 0.0012840 </td>\n   <td style=\"text-align:center;\"> -0.0021505 </td>\n   <td style=\"text-align:center;\"> 0.0069773 </td>\n   <td style=\"text-align:center;\"> -0.0032903 </td>\n   <td style=\"text-align:center;\"> -0.0003065 </td>\n   <td style=\"text-align:center;\"> 0.0083825 </td>\n   <td style=\"text-align:center;\"> 0.0023079 </td>\n   <td style=\"text-align:center;\"> -0.0031543 </td>\n   <td style=\"text-align:center;\"> 0.0033854 </td>\n   <td style=\"text-align:center;\"> 0.0098949 </td>\n   <td style=\"text-align:center;\"> -0.0030851 </td>\n   <td style=\"text-align:center;\"> 0.0039186 </td>\n   <td style=\"text-align:center;\"> -0.0078655 </td>\n   <td style=\"text-align:center;\"> -0.0045608 </td>\n   <td style=\"text-align:center;\"> -0.0119175 </td>\n   <td style=\"text-align:center;\"> -0.0103131 </td>\n   <td style=\"text-align:center;\"> -0.0110881 </td>\n   <td style=\"text-align:center;\"> 0.0006284 </td>\n   <td style=\"text-align:center;\"> 0.0005791 </td>\n   <td style=\"text-align:center;\"> -0.0074469 </td>\n   <td style=\"text-align:center;\"> 0.0023064 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Y[t+1] = Y[t] </td>\n   <td style=\"text-align:center;\"> 0.0024552 </td>\n   <td style=\"text-align:center;\"> 0.0025186 </td>\n   <td style=\"text-align:center;\"> 0.0005306 </td>\n   <td style=\"text-align:center;\"> 0.0065276 </td>\n   <td style=\"text-align:center;\"> -0.0058184 </td>\n   <td style=\"text-align:center;\"> -0.0016579 </td>\n   <td style=\"text-align:center;\"> -0.0014994 </td>\n   <td style=\"text-align:center;\"> 0.0059232 </td>\n   <td style=\"text-align:center;\"> 0.0027372 </td>\n   <td style=\"text-align:center;\"> 0.0065781 </td>\n   <td style=\"text-align:center;\"> -0.0013772 </td>\n   <td style=\"text-align:center;\"> 0.0055886 </td>\n   <td style=\"text-align:center;\"> -0.0020806 </td>\n   <td style=\"text-align:center;\"> -0.0041978 </td>\n   <td style=\"text-align:center;\"> -0.0008571 </td>\n   <td style=\"text-align:center;\"> 0.0029363 </td>\n   <td style=\"text-align:center;\"> 0.0009000 </td>\n   <td style=\"text-align:center;\"> 0.0084680 </td>\n   <td style=\"text-align:center;\"> -0.0024213 </td>\n   <td style=\"text-align:center;\"> 0.0053036 </td>\n   <td style=\"text-align:center;\"> 0.0030215 </td>\n   <td style=\"text-align:center;\"> 0.0082589 </td>\n   <td style=\"text-align:center;\"> 0.0030677 </td>\n   <td style=\"text-align:center;\"> -0.0003668 </td>\n   <td style=\"text-align:center;\"> 0.0087610 </td>\n   <td style=\"text-align:center;\"> -0.0015066 </td>\n   <td style=\"text-align:center;\"> 0.0014772 </td>\n   <td style=\"text-align:center;\"> 0.0101662 </td>\n   <td style=\"text-align:center;\"> 0.0040916 </td>\n   <td style=\"text-align:center;\"> -0.0013707 </td>\n   <td style=\"text-align:center;\"> 0.0051690 </td>\n   <td style=\"text-align:center;\"> 0.0116786 </td>\n   <td style=\"text-align:center;\"> -0.0013015 </td>\n   <td style=\"text-align:center;\"> 0.0057023 </td>\n   <td style=\"text-align:center;\"> -0.0060818 </td>\n   <td style=\"text-align:center;\"> -0.0027771 </td>\n   <td style=\"text-align:center;\"> -0.0101338 </td>\n   <td style=\"text-align:center;\"> -0.0085294 </td>\n   <td style=\"text-align:center;\"> -0.0093044 </td>\n   <td style=\"text-align:center;\"> 0.0024120 </td>\n   <td style=\"text-align:center;\"> 0.0023628 </td>\n   <td style=\"text-align:center;\"> -0.0056632 </td>\n   <td style=\"text-align:center;\"> 0.0040900 </td>\n  </tr>\n</tbody>\n</table></div>\n\n`````\n:::\n:::\n\n\nPode-se melhor comparar a performance das previsões usando alguma medida agregada de erro. Duas medidas bastante comuns são o Erro Absoluto Médio (EAM) e o Erro Quadrático Médio. A primeira toma o módulo da diferença entre o previsto ($\\hat{y}$) e o observado ($y$) e tira uma média, enquanto a última toma a diferença quadrática. Formalmente, para um horizonte de previsão $h$ começando na última observação $T$:\n\n\n```{=tex}\n\\begin{align}\n\\text{EAM} & = \\frac{1}{h}\\sum_{i = T + 1}^{T + h} |y_{i} - \\hat{y}_{i}| \\\\\n\\text{EQM} & = \\frac{1}{h}\\sum_{i = T + 1}^{T + h} (y_{i} - \\hat{y}_{i})^2\n\\end{align}\n```\n\nA tabela abaixo compara os modelos segundo estas medidas de erro.\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n::: {.cell layout-align=\"center\" asis='true'}\n::: {.cell-output-display}\n`````{=html}\n<div style=\"border: 1px solid #ddd; padding: 5px; overflow-x: scroll; width:100%; \"><table class=\"table table-striped table-bordered table-hover\" style=\"margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:left;\">   </th>\n   <th style=\"text-align:center;\"> EAM </th>\n   <th style=\"text-align:center;\"> EQM </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> ARMA(1, 2) </td>\n   <td style=\"text-align:center;\"> 0.0042173 </td>\n   <td style=\"text-align:center;\"> 0.0042062 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> ARMA(1, 1) </td>\n   <td style=\"text-align:center;\"> 0.0000268 </td>\n   <td style=\"text-align:center;\"> 0.0000268 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> AR(1) </td>\n   <td style=\"text-align:center;\"> 0.0042143 </td>\n   <td style=\"text-align:center;\"> 0.0043644 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Y[t+1] = Y[t] </td>\n   <td style=\"text-align:center;\"> 0.0000268 </td>\n   <td style=\"text-align:center;\"> 0.0000280 </td>\n  </tr>\n</tbody>\n</table></div>\n\n`````\n:::\n:::\n\n\nNem sempre é fácil comparar estas medidas, i.e., verificar se elas são estatisticamente significantes. Pode-se usar o teste Diebold-Mariano para comparar estas medidas de erro, mas é importante frisar que ele contém uma série de hipóteses sobre a distribuição dos erros. A função `dm.test` do pacote `forecast` faz este teste e mais informações sobre ele podem ser encontradas usando `?dm.test`.\n\nPode-se visualizar as previsões usando as funções `autoplot()` e `autolayer()` do pacote `forecast`. Abaixo mostro os resultados para o modelo AR(1) e também para o modelo ingênuo. note como o erros-padrão deste último cresce muito rapidamente (pois a variância de um processo random-walk cresce sem limite).\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\nautoplot(prev2, include = 50) +\n  autolayer(teste) +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-21-1.svg){fig-align='center' width=90%}\n:::\n\n```{.r .cell-code}\n\nautoplot(prev3, include = 50) +\n  autolayer(teste) +\n  labs(x = \"\", y = \"(%)\") + \n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-21-2.svg){fig-align='center' width=90%}\n:::\n\n```{.r .cell-code}\n\nautoplot(prev4, include = 50) +\n  autolayer(teste) +\n  labs(x = \"\", y = \"(%)\") + \n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-21-3.svg){fig-align='center' width=90%}\n:::\n:::\n\n\n# Conclusão\n\nOs modelos da classe ARMA são bastante populares em séries de tempo pois geram boas previsões de curto prazo. Além disso, estes modelos são estimados facilmente e usam apenas a informação da própria série. No post acima, vimos como estimar um modelo ARMA e algumas das facilidades que tanto o pacote `astsa` como o `forecast` nos oferecem.\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../../../site_libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"../../../site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}