---
title: "Hiperinflation: a Brazilian journey"
categories: ['brasil', 'data-visualization']
draft: true
---

```{r}
library(ggplot2)
sysfonts::font_add("Helvetica", "Helvetica.ttc")
showtext::showtext_auto()

ipca <- GetBCBData::gbcbd_get_series(433, first.date = as.Date("1980-01-01"))

ipca <- ipca |> 
  dplyr::rename(date = ref.date)
```

```{r}
df <- tidyr::tribble(
  ~date, ~event, ~date_label,
  "1980-01-01", "Delfim + Oil Crisis", "Dez 1989",
  "1983-02-01", "Delfim (2nd)", "Fev 1983",
  "1985-05-01", "Military Regime Ends", NA,
  "1986-04-01", "Cruzado Plan", "Fev 1986",
  "1987-08-01", "Bresser Plan", "Jun 1987",
  "1989-03-01", "Verão Plan", "Jan 1989",
  "1990-05-01", "Collor Plan", "Mar 1990",
  "1991-04-01", "Collor II Plan", "Jan 1991",
  "1994-08-01", "Real Plan", "Jul 1994",
  "1999-01-01", "Flotaing Exchange Rate", "Jan 1999",
  "2002-11-01", "Argentina + Lula", "2002/2003",
  "2008-07-01", "Great Financial Recession", "2008",
  "2016-08-01", "Dilma Impeachment", "2016",
  "2020-03-01", "Covid-19", "Mar 2019"
)

df <- dplyr::mutate(df, date = as.Date(date))

events <- dplyr::left_join(df, ipca, by = "date")
```

```{r}
ggplot() +
  geom_area(
    data = ipca,
    aes(x = date, y = value),
    fill = "gray50") +
  geom_point(
    data = events,
    aes(x = date, y = value),
    shape = 21,
    fill = "#de2d26",
    color = "gray90"
  ) +
  geom_hline(yintercept = 0) +
  labs(
    title = "The Story of Brazilian Inflation",
    subtitle = "Monthly percent variation in Consumer Price Index",
    caption = "Source: IBGE",
    x = NULL,
    y = "IPCA\n(MoM, %)") +
  theme_minimal(base_family = "Helvetica") +
  theme(
    panel.grid.minor = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.major.y = element_line(linetype = 2),
    plot.title = element_text(size = 18),
    axis.text.x = element_text(size = 12),
    axis.text.y = element_text(size = 10),
    axis.title.y = element_text(size = 12, angle = 0, vjust = 1)
  )
```

```{r}
subipca <- ipca |> 
  dplyr::mutate(acum = RcppRoll::roll_prodr(1 + value / 100, n = 12) - 1) |> 
  dplyr::filter(date >= as.Date("1995-07-01"))

df <- tidyr::tribble(
  ~date, ~event, ~date_label,
  "1999-01-01", "Flotaing Exchange Rate", "Lowest YoY Inflation",
  "2002-11-01", "Argentina + Lula", "2002/2003",
  "2008-07-01", "Great Financial Recession", "2008",
  "2016-08-01", "Dilma Impeachment", "2016",
  "2020-03-01", "Covid-19", "Mar 2019",
  "2022-04-01", "Pandemic Peak", "12,1%"
)

df <- dplyr::mutate(df, date = as.Date(date))

events <- dplyr::left_join(df, subipca, by = "date")
```

```{r}


ggplot(subipca, aes(x = date, y = acum)) +
  geom_area(fill = "#fcbba1") +
  geom_point(
    data = events,
    aes(x = date, y = acum),
    color = "#cb181d"
  ) +
  geom_hline(yintercept = 0) +
  scale_x_date(expand = c(0, 0)) +
  scale_y_continuous(
    breaks = seq(0, 0.25, 0.05),
    labels = scales::label_percent(decimal.mark = ","),
    limits = c(NA, 0.35)
    ) +
  theme_minimal(base_family = "Helvetica") +
  theme(
    panel.grid.minor = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.major.y = element_line(linetype = 2),
    plot.title = element_text(size = 18),
    axis.text.x = element_text(size = 12),
    axis.text.y = element_text(size = 10),
    axis.title.y = element_text(size = 12, angle = 0, vjust = 0.7)
  )
```

```{r}
subipca |> 
  dplyr::filter(date >= as.Date("2020-01-01")) |> 
  dplyr::slice_max(acum, n = 5)
```
