---
title: "O crescimento das Regiões Metropolitanas segundo o Censo 2022"
date: "2025-06-15"
categories: ["censo", "brasil", "cidades", "demografia", "data-visualization"]
description: " "
format: html
execute:
  message: false
  warning: false
  echo: false
draft: true
---

```{r}
library(dplyr)
library(gt)
library(gtExtras)
```

```{r}
tables <- qs::qread(
  here::here("posts/general-posts/2025-06-censo-metro-regions/table.qs")
)

metro <- tables$metro
metro_wide <- tables$metro_wide
```

```{r}
timeline <- metro %>%
  summarise(
    TCG = list(na.omit(c(tcg * 100))),
    .by = "name_metro"
  )

col_names <- c(
  "Região Metro", "Estado", "1991", "2000", "2010", "2022", "1991/2000", "2000/2010",
  "2010/2022"
)

names(col_names) <- names(metro_wide)

gtable_cities <- metro_wide %>%
  left_join(timeline) %>%
  gt() %>%
  cols_label(.list = col_names) %>%
  tab_spanner("População (Mil)", columns = 3:6) %>%
  tab_spanner("Crescimento (%)", columns = 7:9) %>%
  fmt_number(starts_with("total"), decimals = 0, sep_mark = ".") %>%
  fmt_percent(starts_with("tcg"), decimals = 2) %>%
  ## Target Timeline column
  gt_plt_sparkline(
    column = TCG,
    palette = c("gray30", "black", "firebrick", "dodgerblue", "lightgrey"),
    fig_dim = c(5, 28)
  ) %>%
  gt_theme_538() %>%
  gt_color_rows(
    columns = tcg_2022,
    domain = seq(-0.005, 0.03, 0.005),
    #domain = c(min(metro_wide$tcg_2022), 0, max(metro_wide$tcg_2022)),
    palette = c(
      "#E63946", "#F1FAEE", "#CDEAE5", "#BBE2E1", "#A8DADC", "#90C3CD", "#77ABBD",
      "#457B9D", "#31587A", "#1D3557")
  )
```

```{r}
gtable_cities
```
